/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafici;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author Erli
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        canvas = new java.awt.Canvas();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMoltiplicatore = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(810, 770));
        setResizable(false);
        getContentPane().setLayout(null);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Action(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Action(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(90, 610, 460, 50);

        canvas.setMaximumSize(new java.awt.Dimension(780, 580));
        canvas.setMinimumSize(new java.awt.Dimension(780, 580));
        canvas.setName(""); // NOI18N
        canvas.setPreferredSize(new java.awt.Dimension(780, 580));
        getContentPane().add(canvas);
        canvas.setBounds(10, 10, 780, 580);
        canvas.getAccessibleContext().setAccessibleName("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("f(x) =");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 610, 80, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Fatto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fattoAction(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(560, 610, 100, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Pulisci");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulisciAction(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(670, 610, 120, 50);

        jMoltiplicatore.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMoltiplicatore.setText("10");
        jMoltiplicatore.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jValoriActionPerformed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jValoriActionPerformed(evt);
            }
        });
        getContentPane().add(jMoltiplicatore);
        jMoltiplicatore.setBounds(230, 670, 100, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Scala");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 670, 70, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Precisione");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 670, 100, 40);

        jSlider1.setMaximum(50);
        jSlider1.setMinimum(10);
        jSlider1.setToolTipText("");
        jSlider1.setValue(30);
        jSlider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                updateValoriPianoCartesiano(evt);
            }
        });
        getContentPane().add(jSlider1);
        jSlider1.setBounds(480, 680, 200, 26);

        jLabel4.setText("Min");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(460, 680, 34, 30);

        jLabel6.setText("Max");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(680, 680, 50, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Action(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Action
        if (init == false) {
            init();
            drawPiano();
        }
        if (!(jMoltiplicatore.getText().equals("")))
            updateValoriPianoCartesiano();
    }//GEN-LAST:event_Action

    private void fattoAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fattoAction
        
        g2.setColor(nextColor());
        
        Funzione f = new Funzione(jTextField1.getText());

        for (double i = -max;i < max;i += step) {
            //System.out.println(i);
            draw(new Punto((int) (i * mol), (int) (f.calcFun(i) * mol), canvas));
        }
        
    }//GEN-LAST:event_fattoAction

    private void pulisciAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulisciAction
        init();
        g2.clearRect(0, 0, canvas.getWidth(), canvas.getHeight());
        drawPiano();
    }//GEN-LAST:event_pulisciAction

    private void jValoriActionPerformed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jValoriActionPerformed
        if (!(jMoltiplicatore.getText().equals("")))
            updateValoriPianoCartesiano();
    }//GEN-LAST:event_jValoriActionPerformed

    private void updateValoriPianoCartesiano(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateValoriPianoCartesiano
        if (!(jMoltiplicatore.getText().equals("")))
            updateValoriPianoCartesiano();
    }//GEN-LAST:event_updateValoriPianoCartesiano

    double max = 100;
    double step = 0.1;
    double mol = 5; //moltiplicatore
    double calcoli;
    
    Graphics2D g2;
    int contatoreColore = 0;
    boolean init = false;
    Punto lastPunto;
    
    
    public Color nextColor() {
        contatoreColore++;
        Color[] colori = {Color.BLUE, Color.GREEN, Color.RED, Color.YELLOW, Color.LIGHT_GRAY, Color.CYAN, Color.MAGENTA, Color.ORANGE, Color.PINK};
        if (contatoreColore == 9) {
            contatoreColore = 0;
        }
        return colori[contatoreColore];
    }
    public void draw(Punto punto) {
        
        if (!(punto.equals(lastPunto))) {
            g2.drawOval(punto.getCanvasX(), punto.getCanvasY(), 1, 1);
            lastPunto = punto;
        }
        //g2.drawOval(punto.getCanvasX(), punto.getCanvasY(), 1, 1);
    }
    public void drawPiano() {
        g2.setColor(Color.black);
        g2.drawLine(canvas.getWidth()/2, 0,canvas.getWidth()/2, canvas.getHeight());
        g2.drawLine(0, canvas.getHeight()/2,canvas.getWidth(), canvas.getHeight()/2);
        
        g2.drawLine(canvas.getWidth()/2 + 5, + 8, canvas.getWidth()/2, 0);
        g2.drawLine(canvas.getWidth()/2 - 5, + 8, canvas.getWidth()/2, 0);
        
        g2.drawLine(canvas.getWidth(), canvas.getHeight()/2, canvas.getWidth() - 8, canvas.getHeight()/2 + 5);
        g2.drawLine(canvas.getWidth(), canvas.getHeight()/2, canvas.getWidth() - 8, canvas.getHeight()/2 - 5);
    }
    public void init() {
        Graphics g = canvas.getGraphics();
        g2 = (Graphics2D) g;
    }
    public void updateValoriPianoCartesiano() {
        mol = Double.parseDouble(jMoltiplicatore.getText());
        calcoli = Math.pow(3, (((double) jSlider1.getValue()) / 10)) * 300;
        //System.out.println("Calcoli: " + calcoli);
        max = 390/mol;
        step = max/calcoli;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jMoltiplicatore;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
